export const LOAD_COURSES_SUCCESS = 'courses/LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'authors/LOAD_AUTHORS_SUCCESS';
export const UPDATE_COURSES_SUCCESS = 'authors/UPDATE_COURSES_SUCCESS';
export const CREATE_COURSES_SUCCESS = 'authors/CREATE_COURSES_SUCCESS';
export const BEGIN_AJAX_CALL = 'ajax/BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'ajax/AJAX_CALL_ERROR';


